trigger:
  branches:
    include:
      - main  # Adjust to the branch you want to trigger builds on

pool:
  vmImage: 'ubuntu-latest'

steps:

  # Step 1: Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'  # Specify Node.js version, such as 14.x or 16.x
    displayName: 'Install Node.js'

  # Step 2: Install Dependencies
  - script: |
      npm install
    displayName: 'Install Node.js Dependencies'

  # Authenticate with Azure DevOps using the PAT token
  - script: |
      echo $(naga-pat) | az devops login --organization https://dev.azure.com/CloudBuildersTech/
    displayName: 'Authenticate Azure DevOps CLI'

  - task: UniversalPackages@0
    inputs:
      command: 'publish'
      publishDirectory: '$(System.DefaultWorkingDirectory)'
      vstsFeedPublish: 'CB-CommonProject/testing-credo'
      vstsFeedPackagePublish: 'my-first-package'
      versionOption: 'custom'
      versionPublish: '1.0.$(Build.BuildId)'
      packagePublishDescription: 'Welcome to Universal Packages'

