trigger:
  branches:
    include:
      - main  # Adjust to the branch you want to trigger builds on

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'  # Specify Node.js version, such as 14.x or 16.x
    displayName: 'Install Node.js'

  # Step 2: Install Dependencies
  - script: |
      npm install
    displayName: 'Install Node.js Dependencies'

  # Optional Step 3: Run Build Command
  # Skip this step if there is no build process
  # Uncomment if you add a build process to the application in the future
  # - script: |
  #     npm run build
  #   displayName: 'Build Application'
  #   condition: succeeded()  # Only run if the previous steps succeeded

  # Step 4: Prepare Artifact for Deployment
  - script: |
      mkdir -p $(Build.ArtifactStagingDirectory)/app
      cp -R * $(Build.ArtifactStagingDirectory)/app
    displayName: 'Copy Files to Artifact Staging Directory'

  # Step 5: Publish Build Artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/app'
      artifactName: 'app'
    displayName: 'Publish Build Artifacts'
